# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: aws-cli 
    before:
      cd/workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install   
      cd $THEIA_WORKSPACE_ROOT 


gp env AWS_ACCESS_KEY_ID=AKIA5FTZDI2KSWGEA24A
gp env AWS_SECRET_ACCESS_KEY=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
gp env AWS_DEFAULT_REGION=us-east-1
  